{{/*
MIT License

(C) Copyright 2021-2024 Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name:  "{{ include "cray-service.name" . }}-migration"
  labels:
    app.kubernetes.io/managed-by: "{{ include "cray-service.name" . }}"
    app.kubernetes.io/instance: "{{ include "cray-service.name" . }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-1"


spec:
  # Set ttlSecondsAfterFinished to 28 days.
  # Because the migration can delete BOS data, but logs when it does so,
  # this allows its logs to be easily accesible for longer post-upgrade
  ttlSecondsAfterFinished: 2419200
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by:  "{{ include "cray-service.name" . }}"
        app.kubernetes.io/instance:  "{{ include "cray-service.name" . }}"
        app.kubernetes.io/name:  "{{ include "cray-service.name" . }}-migration"
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "2379,2380,6379"
        "proxy.istio.io/config": '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      serviceAccountName: "{{ include "cray-service.name" . }}-migration"
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      initContainers: []
      containers:
      - name: bos-migrations
        image: {{ index .Values "cray-service" "containers" "cray-bos" "image" "repository" }}:{{ .Chart.AppVersion}}
        command:
          - python3
          - "-m"
          - "bos.server.migrations"
        env:
        - name: APP_VERSION
          value: 0.0.0-app-version
        {{ range (index .Values "cray-service" "containers" "cray-bos" "ports") -}}
        {{if eq .name "http" }}
        - name: BOS_CONTAINER_PORT
          value: "{{ .containerPort }}"
        {{ end }}
        {{- end }}
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
