apiVersion: batch/v1
kind: Job
metadata:
  name:  "{{ include "cray-service.name" . }}-session-template-migration-jobs"
  labels:
    app.kubernetes.io/managed-by: "{{ include "cray-service.name" . }}"
    app.kubernetes.io/instance: "{{ include "cray-service.name" . }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded

spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by:  "{{ include "cray-service.name" . }}"
        app.kubernetes.io/instance:  "{{ include "cray-service.name" . }}"
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: v1-v2-session-template-migration 
        image: index .Values "cray-service" "containers" "cray-bos" "image" "respository" 
        command:
          - python3
          - "-m"
          - "v1_v2_migration"