# Copyright 2019 Cray Inc. All Rights Reserved.
Name: bos-crayctldeploy
License: Cray Software License Agreement
Summary: Boot Orchestration Services (BOS)
Group: System/Management
Version: %(cat .rpm_version)
Release: %(echo ${BUILD_METADATA})
Source: %{name}-%{version}.tar.bz2
Vendor: Cray Inc.
BuildRequires: python3 >= 3.6.8
Requires: cray-crayctl
Requires: cray-cmstools-crayctldeploy
Requires: kubernetes-crayctldeploy

# Project level defines TODO: These should be defined in a central location; DST-892
%define afd /opt/cray/crayctl/ansible_framework
%define modules %{afd}/library

%description
Boot Orchestration Service (BOS) is a restful API that manages
imperative, reproducible state of the managed plane environment and primarily
supports the boot and shutdown of the system.

This rpm provides an Ansible module that allows easy creation of BOS Session
templates.

%package session-template
Summary: Boot Orchestration Services (BOS)
Group: System/Management
Version: 1.0.0
Requires: python3 >= 3.6.8
%description session-template
This rpm provides a command line script that takes JSON input and creates a
BOS session template utilizing the BOS API. This allows for easy template
creation using easily readable and editable JSON input

%prep
%setup -q

%build

python3 tools/setup.py build

%install
# Ansible module
install -m 755 -d %{buildroot}%{modules}/
install -D -m 644 lib/bos_session_template_create.py %{buildroot}%{modules}/bos_session_template_create.py
# Install smoke tests under /opt/cray/tests/crayctl-stage4
mkdir -p ${RPM_BUILD_ROOT}/opt/cray/tests/crayctl-stage4/cms/
cp ct-tests/bos_stage4_ct_tests.sh ${RPM_BUILD_ROOT}/opt/cray/tests/crayctl-stage4/cms/bos_stage4_ct_tests.sh

# bos_session_template.py commandline script
python3 tools/setup.py install -O1 --root="$RPM_BUILD_ROOT" --record=INSTALLED_FILES \
                             --install-scripts=/usr/bin
# This is a hack taken from the DST-EXAMPLES / example-rpm-python repo to get
# the package directory, i.e. /usr/lib/python3.6/site-packages/sat which is not
# included in the INSTALLED_FILES list generated by setup.py.
# TODO: Replace this hack with something better, perhaps using %python_sitelib
cat INSTALLED_FILES | grep __pycache__ | xargs dirname | xargs dirname | uniq >> INSTALLED_FILES

%clean
rm -f  %{buildroot}%{modules}/*

%files
%defattr(755, root, root)
%{modules}/bos_session_template_create.py

/opt/cray/tests/crayctl-stage4/cms/bos_stage4_ct_tests.sh

%files session-template -f INSTALLED_FILES
