apiVersion: v1
description: "Kubernetes resources for BOS"
name: "cray-bos"
home: "scms/bos"
version: 1.6.10
keywords:
  - bos
  - boa
  - cray-bos
sources:
  - "https://stash.us.cray.com/projects/SCMS/repos/bos/browse"
maintainers:
  - name: Ryan
    email: ryan.bak@hpe.com
  - name: Rob
    email: robert.noska@hpe.com
  - name: Jason
    email: jason.sollom@hpe.com
