# Copyright 2020 Hewlett Packard Enterprise Development LP

"""
Test helper functions
"""

from common.helpers import debug, info, raise_test_error
import datetime
import json

DEFAULT_TEMPLATE_PATH = "/opt/cray/tests/dat/cms/bos_functional_test/bos_session_template.json"

def generate_session_template():
    """
    Loads the default template from the JSON file, sets the name and description, and returns it
    """
    info("Loading default template from %s" % DEFAULT_TEMPLATE_PATH)
    with open(DEFAULT_TEMPLATE_PATH, "rt") as f:
        template_object = json.load(f)
    now = datetime.datetime.now()
    debug("Setting description field")
    template_object["description"] = "Generated by BOS functional test %s" % str(now)
    debug("Setting name field")
    template_object["name"] = "test-%s" % now.strftime("%Y%m%d-%H%M%S.%f")
    return template_object

def verify_template_list(template_map, template_name, should_exist):
    """
    If should_exist is true, verifies that the specified template appears in the list.
    If should_exist is false, verifies that it does not.
    """
    for tname in template_map.keys():
        if tname != template_name:
            continue
        elif should_exist:
            info("Found %s in template list" % template_name)
            return
        else:
            raise_test_error("Found %s in template list, but it should not be present" % template_name)
    if should_exist:
        raise_test_error("Did not find %s in template list, but it should have been present" % template_name)
    info("Confirmed that %s is not present in template list" % template_name)
